---
- hosts: test
  gather_facts: false
  vars_prompt:
    - name: "one"
      prompt: "please input on value"
      private: no
    - name: "two"
      prompt: "please input two value"
      default: 'good'
      private: yes
  tasks:
    - name: display one value
      debug: msg=" one value is {{ one }} "
    - name: display two value
      debug: msg="two value is  {{ two }}"
